/*
 Navicat MySQL Data Transfer

 Source Server         : Localhost
 Source Server Type    : MySQL
 Source Server Version : 50725
 Source Host           : localhost:3306
 Source Schema         : boot

 Target Server Type    : MySQL
 Target Server Version : 50725
 File Encoding         : 65001

 Date: 10/05/2019 16:43:26
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ap_states
-- ----------------------------
DROP TABLE IF EXISTS `ap_states`;
CREATE TABLE `ap_states` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `country` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `state` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `code` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nickname` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `capital` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL,
  `full_width_image` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_attribution` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `alt_text` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `image_caption` varchar(191) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  KEY `states_country_index` (`country`) USING BTREE,
  KEY `states_state_index` (`state`) USING BTREE,
  KEY `states_code_index` (`code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=66 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of ap_states
-- ----------------------------
BEGIN;
INSERT INTO `ap_states` VALUES (2, 'USA', 'Alabama', 'AL', 'The Yellowhammer State', 'Montgomery', 'https://media1.moneywise.com/a/2375/real-estate_full_width_2_1200x500_v20181026032235.jpg', 'N.A. Qurashi / Shutterstock', 'A cool evening in Fairhope, Alabama', 'A cool evening in Fairhope, Alabama', NULL, NULL);
INSERT INTO `ap_states` VALUES (3, 'USA', 'Alaska', 'AK', 'The Last Frontier', 'Juneau', 'https://media1.moneywise.com/a/2375/real-estate_full_width_3_1200x500_v20181026032505.jpg', 'Christopher Boswell / Shutterstock', 'A panoramic view of tundra and mountainous landscape in the last frontier of Alaska', 'A panoramic view of tundra and mountainous landscape in the last frontier of Alaska', NULL, NULL);
INSERT INTO `ap_states` VALUES (4, 'USA', 'Arizona', 'AZ', 'The Grand Canyon State', 'Phoenix', 'https://media1.moneywise.com/a/2375/real-estate_full_width_4_1200x500_v20181026032620.jpg', 'f11photo / Shutterstock', 'Monument Valley twilight, AZ, USA', 'Monument Valley, Arizona', NULL, NULL);
INSERT INTO `ap_states` VALUES (5, 'USA', 'Arkansas', 'AR', 'The Natural State', 'Little Rock', 'https://media1.moneywise.com/a/2375/real-estate_full_width_5_1200x500_v20181026032748.jpg', 'Zack Frank / Shutterstock', 'A grand view of Mount Magazine State Park', 'A grand view of Mount Magazine State Park', NULL, NULL);
INSERT INTO `ap_states` VALUES (6, 'USA', 'California', 'CA', 'The Golden State', 'Sacramento', 'https://media1.moneywise.com/a/2375/real-estate_full_width_6_1200x500_v20181026032854.jpg', 'IM_photo / Shutterstock', 'Los Angeles hot sunset view with palm tree and downtown in background. California', 'A view of the Los Angeles, California skyline at sunset', NULL, NULL);
INSERT INTO `ap_states` VALUES (7, 'USA', 'Colorado', 'CO', 'The Centennial State', 'Denver', 'https://media1.moneywise.com/a/2375/real-estate_full_width_7_1200x500_v20181026033017.jpg', 'shaferaphoto / Shutterstock', 'A ranch fence overlooking Mount Wilson, Colorado', 'A ranch fence overlooking Mount Wilson, Colorado', NULL, NULL);
INSERT INTO `ap_states` VALUES (8, 'USA', 'Connecticut', 'CT', 'The Constitution State', 'Hartford', 'https://media1.moneywise.com/a/2375/real-estate_full_width_8_1200x500_v20181026033140.jpg', 'Jon Bilous / Shutterstock', 'A view of the skyline and the Connecticut State Capitol Building in Hartford, Connecticut.', 'A view of the skyline and the Connecticut State Capitol Building in Hartford, Connecticut.', NULL, NULL);
INSERT INTO `ap_states` VALUES (9, 'USA', 'Delaware', 'DE', 'The First State', 'Dover', 'https://media1.moneywise.com/a/2375/real-estate_full_width_9_1200x500_v20181026033343.jpg', 'Al Jurina / Shutterstock', 'Bethany Beach Delaware', 'Bethany Beach, Delaware is a popular relaxation destination for the local population', NULL, NULL);
INSERT INTO `ap_states` VALUES (10, 'USA', 'District of Columbia', 'DC', 'The Nation\'s Capital', 'Washington', 'https://media1.moneywise.com/a/2375/real-estate_full_width_10_1200x500_v20181026033459.jpg', 'Sean Pavone / Shutterstock', 'Washington, D.C. skyline with highways and monuments.', 'Washington, D.C. skyline with highways and monuments', NULL, NULL);
INSERT INTO `ap_states` VALUES (11, 'USA', 'Florida', 'FL', 'The Sunshine State', 'Tallahassee', 'https://media1.moneywise.com/a/2375/real-estate_full_width_11_1200x500_v20181026033606.jpg', 'ESB Professional / Shutterstock', 'Orlando, Florida, USA downtown city skyline on Eola Lake.', 'Orlando, Florida downtown city skyline on Eola Lake', NULL, NULL);
INSERT INTO `ap_states` VALUES (12, 'USA', 'Georgia', 'GA', 'The Peach State', 'Atlanta', 'https://media1.moneywise.com/a/2375/real-estate_full_width_12_1200x500_v20181026034112.jpg', 'Sean Pavone / Shutterstock', 'Athens, Georgia, USA downtown at sunset.', 'Athens, Georgia, USA downtown at sunset.', NULL, NULL);
INSERT INTO `ap_states` VALUES (13, 'USA', 'Hawaii', 'HI', 'The Aloha State', 'Honolulu', 'https://media1.moneywise.com/a/2375/real-estate_full_width_13_1200x500_v20181026034237.jpg', 'Izabela23 / Shutterstock', 'Skyline of Honolulu, Hawaii and the surrounding area including the hotels and buildings on Waikiki Beach', 'Skyline of Honolulu, Hawaii and the surrounding area including the hotels and buildings on Waikiki Beach', NULL, NULL);
INSERT INTO `ap_states` VALUES (14, 'USA', 'Idaho', 'ID', 'The Gem State', 'Boise', 'https://media1.moneywise.com/a/2375/real-estate_full_width_14_1200x500_v20181026034341.jpg', 'Charles Knowles / Shutterstock', 'Boise Idaho street leading to the capital building in fall', 'Boise Idaho street leading to the capital building in fall', NULL, NULL);
INSERT INTO `ap_states` VALUES (15, 'USA', 'Illinois', 'IL', 'The Prairie State', 'Springfield', 'https://media1.moneywise.com/a/2375/real-estate_full_width_15_1200x500_v20181026034549.jpg', 'marchello74 / Shutterstock', 'Typical Suburbs Buildings Against Chicago Downtown - wide angle', 'A view from the suburbs all the way to downtown Chicago, Illinois', NULL, NULL);
INSERT INTO `ap_states` VALUES (16, 'USA', 'Indiana', 'IN', 'The Hoosier State', 'Indianapolis', 'https://media1.moneywise.com/a/2375/real-estate_full_width_16_1200x500_v20181026034735.jpg', 'f11photo / Shutterstock', 'Downtown of Indianapolis by Indiana Central Canal', 'Downtown of Indianapolis by Indiana Central Canal', NULL, NULL);
INSERT INTO `ap_states` VALUES (17, 'USA', 'Iowa', 'IA', 'The Hawkeye State', 'Des Moines', 'https://media1.moneywise.com/a/2375/real-estate_full_width_17_1200x500_v20181026034849.jpg', 'Felix Mizioznikov / Shutterstock', 'Aerial image of single family homes in Bettendorf Iowa USA', 'Aerial image of single family homes in Bettendorf, Iowa', NULL, NULL);
INSERT INTO `ap_states` VALUES (18, 'USA', 'Kansas', 'KS', 'The Sunflower State', 'Topeka', 'https://media1.moneywise.com/a/2375/real-estate_full_width_18_1200x500_v20181026035003.jpg', 'Sean Pavone / Shutterstock', 'Wichita, Kansas, USA downtown skyline at dusk.', 'Wichita, Kansas, USA downtown skyline at dusk', NULL, NULL);
INSERT INTO `ap_states` VALUES (19, 'USA', 'Kentucky', 'KY', 'The Bluegrass State', 'Frankfort', 'https://media1.moneywise.com/a/2375/real-estate_full_width_19_1200x500_v20181026035308.jpg', 'Sean Pavone / Shutterstock', 'Louisville, Kentucky, USA skyline on the river.', 'Louisville, Kentucky, USA skyline on the river.', NULL, NULL);
INSERT INTO `ap_states` VALUES (20, 'USA', 'Louisiana', 'LA', 'The Pelican State', 'Baton Rouge', 'https://media1.moneywise.com/a/2375/real-estate_full_width_20_1200x500_v20181026035408.jpg', 'Sean Pavone / Shutterstock', 'Shreveport, Louisiana, USA downtown skyline over the river.', 'Shreveport, Louisiana, USA downtown skyline over the river.', NULL, NULL);
INSERT INTO `ap_states` VALUES (21, 'USA', 'Maine', 'ME', 'The Pine Tree State', 'Augusta', 'https://media1.moneywise.com/a/2375/real-estate_full_width_21_1200x500_v20181026035504.jpg', 'Sean Pavone / Shutterstock', 'Portland, Maine, USA coastal townscape.', 'Portland, Maine, USA coastal townscape.', NULL, NULL);
INSERT INTO `ap_states` VALUES (22, 'USA', 'Montana', 'MT', 'The Treasure State', 'Helena', 'https://media1.moneywise.com/a/2375/real-estate_full_width_22_1200x500_v20181026035607.jpg', 'Jeremy Janus Photography / Shutterstock', 'Sunset in Montana', 'Sunset in Montana', NULL, NULL);
INSERT INTO `ap_states` VALUES (23, 'USA', 'Nebraska', 'NE', 'The Cornhusker State', 'Lincoln', 'https://media1.moneywise.com/a/2375/real-estate_full_width_23_1200x500_v20181026035730.jpg', 'DomVisuals / Shutterstock', 'Sunset over river and skyline, Omaha, NE.', 'Sunset over river and skyline, Omaha, NE.', NULL, NULL);
INSERT INTO `ap_states` VALUES (24, 'USA', 'Nevada', 'NV', 'The Silver State', 'Carson City', 'https://media1.moneywise.com/a/2375/real-estate_full_width_24_1200x500_v20181026035902.jpg', 'superjoseph / Shutterstock', 'View of the Hoover Dam in Nevada, USA', 'View of the Hoover Dam in Nevada, USA', NULL, NULL);
INSERT INTO `ap_states` VALUES (25, 'USA', 'New Hampshire', 'NH', 'The Granite State', 'Concord', 'https://media1.moneywise.com/a/2375/real-estate_full_width_25_1200x500_v20181026035950.jpg', 'Sean Pavone / Shutterstock', 'Portsmouth, New Hampshire, USA', 'Portsmouth, New Hampshire, USA', NULL, NULL);
INSERT INTO `ap_states` VALUES (26, 'USA', 'New Jersey', 'NJ', 'The Garden State', 'Trenton', 'https://media1.moneywise.com/a/2375/real-estate_full_width_26_1200x500_v20181026040255.jpg', 'mandritoiu / Shutterstock', 'Trenton skyline panorama at dawn. Trenton is the capital of the US state of New Jersey.', 'Trenton skyline panorama at dawn.', NULL, NULL);
INSERT INTO `ap_states` VALUES (27, 'USA', 'New Mexico', 'NM', 'The Land of Enchantment', 'Santa Fe', 'https://media1.moneywise.com/a/2375/real-estate_full_width_27_1200x500_v20181026040436.jpg', 'Jimack / Shutterstock', 'Views of Santa Fe New Mexico', 'Views of Santa Fe New Mexico', NULL, NULL);
INSERT INTO `ap_states` VALUES (28, 'USA', 'New York', 'NY', 'The Empire State', 'Albany', 'https://media1.moneywise.com/a/2375/real-estate_full_width_28_1200x500_v20181026040550.jpg', 'Sean Pavone / Shutterstock', 'New York, New York, USA skyline.', 'New York, New York, USA skyline.', NULL, NULL);
INSERT INTO `ap_states` VALUES (29, 'USA', 'North Carolina', 'NC', 'The Tar Heel State', 'Raleigh', 'https://media1.moneywise.com/a/2375/real-estate_full_width_29_1200x500_v20181026040658.jpg', 'Sean Pavone / Shutterstock', 'Asheville, North Carolina, USA at twilight.', 'Asheville, North Carolina, USA at twilight.', NULL, NULL);
INSERT INTO `ap_states` VALUES (30, 'USA', 'North Dakota', 'ND', 'The Peace Garden State', 'Bismarck', 'https://media1.moneywise.com/a/2375/real-estate_full_width_30_1200x500_v20181026040817.jpg', 'ZakZeinert / Shutterstock', 'Sunrise over Theodore Roosevelt National Park, North Dakota', 'Sunrise over Theodore Roosevelt National Park, North Dakota', NULL, NULL);
INSERT INTO `ap_states` VALUES (31, 'USA', 'Ohio', 'OH', 'The Buckeye State', 'Columbus', 'https://media1.moneywise.com/a/2375/real-estate_full_width_31_1200x500_v20181026040956.jpg', 'Robert  Dunn / Shutterstock', 'Condos and apartments overlooking the Ohio River in Cincinnati', 'Condos and apartments overlooking the Ohio River in Cincinnati', NULL, NULL);
INSERT INTO `ap_states` VALUES (32, 'USA', 'Oklahoma', 'OK', 'The Sooner State', 'Oklahoma City', 'https://media1.moneywise.com/a/2375/real-estate_full_width_32_1200x500_v20181026041138.jpg', 'Hussam Al-Mashhadani / Shutterstock', 'Brick town in Oklahoma', 'Brick town in Oklahoma', NULL, NULL);
INSERT INTO `ap_states` VALUES (33, 'USA', 'Oregon', 'OR', 'The Beaver State', 'Salem', 'https://media1.moneywise.com/a/2375/real-estate_full_width_33_1200x500_v20181026041235.jpg', 'Mike Albright Photography / Shutterstock', 'Aerial View of the Old Mill District in Bend, Oregon, USA', 'Aerial View of the Old Mill District in Bend, Oregon, USA', NULL, NULL);
INSERT INTO `ap_states` VALUES (34, 'USA', 'Maryland', 'MD', 'The Old Line State', 'Annapolis', 'https://media1.moneywise.com/a/2375/real-estate_full_width_34_1200x500_v20181026041324.jpg', 'Sean Pavone / Shutterstock', 'Annapolis, Maryland, USA downtown view over Main Street with the State House.', 'Annapolis, Maryland, USA downtown view over Main Street with the State House.', NULL, NULL);
INSERT INTO `ap_states` VALUES (35, 'USA', 'Massachusetts', 'MA', 'The Bay State', 'Boston', 'https://media1.moneywise.com/a/2375/real-estate_full_width_35_1200x500_v20181026041424.jpg', 'Sean Pavone / Shutterstock', 'Worcester, Massachusetts, USA downtown skyline.', 'Worcester, Massachusetts, USA downtown skyline.', NULL, NULL);
INSERT INTO `ap_states` VALUES (36, 'USA', 'Michigan', 'MI', 'The Great Lakes State', 'Lansing', 'https://media1.moneywise.com/a/2375/real-estate_full_width_36_1200x500_v20181026041706.jpg', 'Gary Richard Ennis / Shutterstock', 'Downtown Traverse City Michigan', 'Downtown Traverse City Michigan', NULL, NULL);
INSERT INTO `ap_states` VALUES (37, 'USA', 'Minnesota', 'MN', 'The North Star State', 'Saint Paul', 'https://media1.moneywise.com/a/2375/real-estate_full_width_37_1200x500_v20181026041929.jpg', 'CK Foto / Shutterstock', 'Minneapolis Minnesota at sunset on the Mississippi river,', 'Minneapolis Minnesota at sunset on the Mississippi river,', NULL, NULL);
INSERT INTO `ap_states` VALUES (38, 'USA', 'Mississippi', 'MS', 'The Magnolia State', 'Jackson', 'https://media1.moneywise.com/a/2375/real-estate_full_width_38_1200x500_v20181026042030.jpg', 'Sean Pavone / Shutterstock', 'Jackson, Mississippi, USA skyline over the Capitol Building.', 'Jackson, Mississippi, USA skyline over the Capitol Building.', NULL, NULL);
INSERT INTO `ap_states` VALUES (39, 'USA', 'Missouri', 'MO', 'The Show Me State', 'Jefferson City', 'https://media1.moneywise.com/a/2375/real-estate_full_width_39_1200x500_v20181026042128.jpg', 'James Roblee / Shutterstock', 'The Gateway Arch in St. Louis, Missouri', 'The Gateway Arch in St. Louis, Missouri', NULL, NULL);
INSERT INTO `ap_states` VALUES (40, 'USA', 'Pennsylvania', 'PA', 'The Keystone State', 'Harrisburg', 'https://media1.moneywise.com/a/2375/real-estate_full_width_40_1200x500_v20181026042317.jpg', 'Jon Bilous / Shutterstock', 'View of Main Street in Shrewsbury, Pennsylvania', 'View of Main Street in Shrewsbury, Pennsylvania', NULL, NULL);
INSERT INTO `ap_states` VALUES (41, 'USA', 'Rhode Island', 'RI', 'The Ocean State', 'Providence', 'https://media1.moneywise.com/a/2375/real-estate_full_width_41_1200x500_v20181026042424.jpg', 'citizensco / Shutterstock', 'Picturesque view of a small town in Rhode Island.', 'Picturesque view of a small town in Rhode Island.', NULL, NULL);
INSERT INTO `ap_states` VALUES (42, 'USA', 'South Carolina', 'SC', 'The Palmetto State', 'Columbia', 'https://media1.moneywise.com/a/2375/real-estate_full_width_42_1200x500_v20181026042525.jpg', 'Sean Pavone / Shutterstock', 'Charleston, South Carolina, USA at the historic homes on The Battery.', 'Charleston, South Carolina, USA at the historic homes on The Battery.', NULL, NULL);
INSERT INTO `ap_states` VALUES (43, 'USA', 'South Dakota', 'SD', 'The Mount Rushmore State', 'Pierre', 'https://media1.moneywise.com/a/2375/real-estate_full_width_43_1200x500_v20181026042729.jpg', 'Jess Kraft / Shutterstock', 'Beautiful Sylvan Lake in Custer State Park', 'Beautiful Sylvan Lake in Custer State Park', NULL, NULL);
INSERT INTO `ap_states` VALUES (44, 'USA', 'Tennessee', 'TN', 'The Volunteer State', 'Nashville', 'https://media1.moneywise.com/a/2375/real-estate_full_width_44_1200x500_v20181026042835.jpg', 'Melinda Fawver / Shutterstock', 'Tennessee River in Knoxville, Tennessee', 'Tennessee River in Knoxville, Tennessee', NULL, NULL);
INSERT INTO `ap_states` VALUES (45, 'USA', 'Texas', 'TX', 'The Lone Star State', 'Austin', 'https://media1.moneywise.com/a/2375/real-estate_full_width_45_1200x500_v20181026042954.jpg', 'f11photo / Shutterstock', 'Dallas, Texas cityscape with blue sky at sunset, Texas', 'Dallas, Texas cityscape with blue sky at sunset, Texas', NULL, NULL);
INSERT INTO `ap_states` VALUES (46, 'USA', 'Utah', 'UT', 'The Beehive State', 'Salt Lake City', 'https://media1.moneywise.com/a/2375/real-estate_full_width_46_1200x500_v20181026043138.jpg', 'Joe Guetzloff / Shutterstock', 'Salt Lake City panorama', 'Salt Lake City panorama', NULL, NULL);
INSERT INTO `ap_states` VALUES (47, 'USA', 'Vermont', 'VT', 'The Green Mountain State', 'Montpelier', 'https://media1.moneywise.com/a/2375/real-estate_full_width_47_1200x500_v20181026142237.jpg', 'Sean Pavone / Shutterstock', 'Montpelier, Vermont, USA town skyline.', 'Montpelier, Vermont, USA town skyline.', NULL, NULL);
INSERT INTO `ap_states` VALUES (48, 'USA', 'Virginia', 'VA', 'The Old Dominion State', 'Richmond', 'https://media1.moneywise.com/a/2375/real-estate_full_width_48_1200x500_v20181026142347.jpg', 'Sean Pavone / Shutterstock', 'Rosslyn, Arlington, Virginia, USA city skyline on the Potomac River.', 'Rosslyn, Arlington, Virginia, USA city skyline on the Potomac River.', NULL, NULL);
INSERT INTO `ap_states` VALUES (49, 'USA', 'Washington', 'WA', 'The Evergreen State', 'Olympia', 'https://media1.moneywise.com/a/2375/real-estate_full_width_49_1200x500_v20181026142445.jpg', 'Jose Luis Stephens / Shutterstock', 'Paradise area at Mount Rainier National Park, Washington State, USA', 'Paradise area at Mount Rainier National Park, Washington State, USA', NULL, NULL);
INSERT INTO `ap_states` VALUES (50, 'USA', 'West Virginia', 'WV', 'The Mountain State', 'Charleston', 'https://media1.moneywise.com/a/2375/real-estate_full_width_50_1200x500_v20181026142527.jpg', 'Sean Pavone / Shutterstock', 'Charleston, West Virginia, USA skyline at dawn.', 'Charleston, West Virginia, USA skyline at dawn.', NULL, NULL);
INSERT INTO `ap_states` VALUES (51, 'USA', 'Wisconsin', 'WI', 'The Badger State', 'Madison', 'https://media1.moneywise.com/a/2375/real-estate_full_width_51_1200x500_v20181026142607.jpg', 'Jay Yuan / Shutterstock', 'Skyline of Madison of Wisconsin at sunset viewing from Olin Turville Park. Photo showing the state capital and lake Monona with reflections, Madison, Wisconsin, USA.', 'Skyline of Madison of Wisconsin at sunset viewing from Olin Turville Park. Photo showing the state capital and lake Monona with reflections, Madison, Wisconsin, USA.', NULL, NULL);
INSERT INTO `ap_states` VALUES (52, 'USA', 'Wyoming', 'WY', 'The Cowboy State', 'Cheyenne', 'https://media1.moneywise.com/a/2375/real-estate_full_width_52_1200x500_v20181026142705.jpg', 'Chase Dekker / Shutterstock', 'The sun sets behind the Teton Range and Snake River in Grand Teton National Park, Wyoming.', 'The sun sets behind the Teton Range and Snake River in Grand Teton National Park, Wyoming.', NULL, NULL);
INSERT INTO `ap_states` VALUES (53, 'Canada', 'Alberta', 'AB', 'Wild Rose Country', 'Edmonton', 'https://media1.moneywise.com/a/2375/real-estate_full_width_53_1200x500_v20181026142818.jpg', 'Sopotnicki / Shutterstock', 'Edmonton downtown after sunset', 'Edmonton downtown after sunset', NULL, NULL);
INSERT INTO `ap_states` VALUES (54, 'Canada', 'British Columbia', 'BC', 'Beautful British Columbia', 'Victoria', 'https://media1.moneywise.com/a/2375/real-estate_full_width_54_1200x500_v20181026142905.jpg', 'Bradley L. Grant / Shutterstock', 'Mount Steven reflects into pond at Field, British Columbia, Canada Located in Yoho National Park.', 'Mount Steven reflects into pond at Field, British Columbia, Canada Located in Yoho National Park.', NULL, NULL);
INSERT INTO `ap_states` VALUES (55, 'Canada', 'Manitoba', 'MB', 'Friendly Manitoba', 'Winnipeg', 'https://media1.moneywise.com/a/2375/real-estate_full_width_55_1200x500_v20181026142951.jpg', 'Nelepl / Shutterstock', 'Winnipeg Autumn', 'Winnipeg Autumn', NULL, NULL);
INSERT INTO `ap_states` VALUES (56, 'Canada', 'New Brunswick', 'NB', 'The Picture Province', 'Fredericton', 'https://media1.moneywise.com/a/2375/real-estate_full_width_56_1200x500_v20181026143128.jpg', 'Albert Pego / Shutterstock', 'Saint John, New Brunswick, from the Reversing Falls Park', 'Saint John, New Brunswick, from the Reversing Falls Park', NULL, NULL);
INSERT INTO `ap_states` VALUES (57, 'Canada', 'Newfoundland and Labrador', 'NL', 'The Rock', 'St. John\'s', 'https://media1.moneywise.com/a/2375/real-estate_full_width_57_1200x500_v20181026143207.jpg', 'Pi-Lens / Shutterstock', 'St. John\'s, capital of Newfoundland Labrador, NL, Canada, harbor and downtown seen from signal hill', 'St. John\'s, capital of Newfoundland Labrador, NL, Canada, harbor and downtown seen from signal hill', NULL, NULL);
INSERT INTO `ap_states` VALUES (58, 'Canada', 'Nova Scotia', 'NS', 'Canada\'s Ocean Playground', 'Halifax', 'https://media1.moneywise.com/a/2375/real-estate_full_width_58_1200x500_v20181026143327.jpg', 'Tom Clausen / Shutterstock', 'A scenic, small fishing village and harbor in the Maritimes', 'A scenic, small fishing village and harbor in the Maritimes', NULL, NULL);
INSERT INTO `ap_states` VALUES (59, 'Canada', 'Ontario', 'ON', 'The Heartland Province', 'Toronto', 'https://media1.moneywise.com/a/2375/real-estate_full_width_59_1200x500_v20181026143418.jpg', 'TRphotos / Shutterstock', 'Sunset over Toronto city skyline in Ontario, Canada', 'Sunset over Toronto city skyline in Ontario, Canada', NULL, NULL);
INSERT INTO `ap_states` VALUES (60, 'Canada', 'Prince Edward Island', 'PE', 'The Cradle of Confederation', 'Charlottetown', 'https://media1.moneywise.com/a/2375/real-estate_full_width_60_1200x500_v20181026143532.jpg', 'Darryl Brooks / Shutterstock', 'Fishing boats in harbor of Charlottetown, Prince Edward Island', 'Fishing boats in harbor of Charlottetown, Prince Edward Island', NULL, NULL);
INSERT INTO `ap_states` VALUES (61, 'Canada', 'Quebec', 'QC', 'Le Belle Province', 'Quebec City', 'https://media1.moneywise.com/a/2375/real-estate_full_width_61_1200x500_v20181026143828.jpg', 'R.M. Nunes / Shutterstock', 'Aerial view of Chateau Frontenac hotel and Old Port in Quebec City, Canada.', 'Aerial view of Chateau Frontenac hotel and Old Port in Quebec City, Canada.', NULL, NULL);
INSERT INTO `ap_states` VALUES (62, 'Canada', 'Saskatchewan', 'SK', 'The Land of the Living Skies', 'Regina', 'https://media1.moneywise.com/a/2375/real-estate_full_width_62_1200x500_v20181026143952.jpg', 'Jeff Whyte / Shutterstock', 'Saskatoon skyline at night along the Saskatchewan River.', 'Saskatoon skyline at night along the Saskatchewan River.', NULL, NULL);
INSERT INTO `ap_states` VALUES (63, 'Canada', 'Northwest Territories', 'NT', 'Canada\'s Last Frontier', 'Yellowknife', 'https://media1.moneywise.com/a/2375/real-estate_full_width_63_1200x500_v20181026144048.jpg', 'Josef Hanus / Shutterstock', 'Yellowknife, Northwest Territories, Canada', 'Yellowknife, Northwest Territories, Canada', NULL, NULL);
INSERT INTO `ap_states` VALUES (64, 'Canada', 'Nunavut', 'NU', 'The Land of the Midnight Sun', 'Iqualuit', 'https://media1.moneywise.com/a/2375/real-estate_full_width_64_1200x500_v20181026144130.jpg', 'Sophia Granchinho / Shutterstock', 'Street view of an arctic community and neigbourhood, located in Arviat, Nunavut Canada', 'Street view of an arctic community and neigbourhood, located in Arviat, Nunavut Canada', NULL, NULL);
INSERT INTO `ap_states` VALUES (65, 'Canada', 'Yukon', 'YT', 'The Land of the Midnight Sun', 'Whitehorse', 'https://media1.moneywise.com/a/2375/real-estate_full_width_65_1200x500_v20181026144328.jpg', 'Tomas Kulaja / Shutterstock', 'The beautiful Kaskawulsh Glacier in Kluane National Park, Yukon, Canada.', 'The beautiful Kaskawulsh Glacier in Kluane National Park, Yukon, Canada.', NULL, NULL);
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
